version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /academy-core
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /deployment/keycloak
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /deployment/erpnext
    schedule:
      interval: monthly
